version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: mutual-fund-api-zookeeper-1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.5
    container_name: mutual-fund-api-kafka-1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  postgres:
    image: postgres:15
    container_name: mutual-fund-api-postgres-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mfund
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mutual-fund-api-redis-1
    ports:
      - "6379:6379"

volumes:
  postgres_data:
