
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mfund
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fund-group
      properties:
        spring.json.trusted.packages: "*"
